public class Bien 
{
   public static void main (String [] args ) 
   {
      String Name ; 
      int Age ;
      float Height;
      Name = "Vũ Lâm Phúc" ;
      Age = 19 ;
      Height = 1.67f ;
      System.out.print ("Ten");
      System.out.println (Name);
      System.out.print ("Tuoi");
      System.out.println(Age);
      System.out.print ("Chieu cao ");
      System.out.println (Height);  
   }
}